# Docker Compose для деплоя full-stack-fastapi-template через Dokploy
# Без Traefik: домены и HTTPS настраиваются в Dokploy.
#
# Обязательно задайте в Dokploy (переменные проекта/окружения):
#   DOMAIN, FRONTEND_HOST, BACKEND_CORS_ORIGINS, SECRET_KEY,
#   FIRST_SUPERUSER, FIRST_SUPERUSER_PASSWORD, POSTGRES_PASSWORD,
#   BACKEND_PUBLIC_URL (публичный URL API для сборки фронтенда)

services:
  db:
    image: postgres:18
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-app}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?POSTGRES_PASSWORD not set}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app}

  prestart:
    image: backend:latest
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: bash scripts/prestart.sh
    env_file:
      - .env
    environment:
      DOMAIN: ${DOMAIN:-localhost}
      FRONTEND_HOST: ${FRONTEND_HOST?FRONTEND_HOST not set}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      SECRET_KEY: ${SECRET_KEY?SECRET_KEY not set}
      FIRST_SUPERUSER: ${FIRST_SUPERUSER?FIRST_SUPERUSER not set}
      FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD?FIRST_SUPERUSER_PASSWORD not set}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      EMAILS_FROM_EMAIL: ${EMAILS_FROM_EMAIL:-noreply@example.com}
      POSTGRES_SERVER: db
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?POSTGRES_PASSWORD not set}
      SENTRY_DSN: ${SENTRY_DSN:-}

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
      prestart:
        condition: service_completed_successfully
    environment:
      DOMAIN: ${DOMAIN:-localhost}
      FRONTEND_HOST: ${FRONTEND_HOST?FRONTEND_HOST not set}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      SECRET_KEY: ${SECRET_KEY?SECRET_KEY not set}
      FIRST_SUPERUSER: ${FIRST_SUPERUSER?FIRST_SUPERUSER not set}
      FIRST_SUPERUSER_PASSWORD: ${FIRST_SUPERUSER_PASSWORD?FIRST_SUPERUSER_PASSWORD not set}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      EMAILS_FROM_EMAIL: ${EMAILS_FROM_EMAIL:-noreply@example.com}
      POSTGRES_SERVER: db
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?POSTGRES_PASSWORD not set}
      SENTRY_DSN: ${SENTRY_DSN:-}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/utils/health-check/')"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Порт для Dokploy: привяжите домен API к этому сервису
    ports:
      - "8000:8000"

  frontend:
    image: frontend:latest
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        # Публичный URL бэкенда (браузер будет слать запросы сюда)
        VITE_API_URL: ${BACKEND_PUBLIC_URL}
        NODE_ENV: production
    restart: always
    depends_on:
      - backend
    # Порт для Dokploy: привяжите домен дашборда к этому сервису
    ports:
      - "80:80"

volumes:
  app-db-data:
